FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y automake libtool clang make cmake

COPY . /repo
WORKDIR /repo/Linux
RUN autoreconf -ivf
RUN mkdir ./dist
RUN ./configure --prefix=/install
RUN make install 

FROM ubuntu:20.04 as package

COPY --from=builder /install /install
